### ISSUE TITLE
Добавление SMS-сервиса

### ISSUE THREAD

**Issue by vuchaev2015** [crinny/b0mb3r#10]
Предлагаю добавить получение кода от Qiwi кошелька

**Comment by FSystem88** [comment]
@vuchaev2015 предлагать это очень конечно хорошо, но с киви тоже не всё так просто.

**Comment by crinny** [comment]
> 
> 
> Предлагаю добавить получение кода от Qiwi кошелька

У Qiwi предоставлена ReCaptcha и в запросе передаётся CSRF токен, так что пока это невозможно.
