### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by koval01** [crinny/b0mb3r#100]
Hi, I did not understand how to run b0mb3r in the terminal (To run spam from the terminal, not through the web interface). So I wrote my script and share it with you. [https://github.com/koval01/my_code/blob/master/b0mb3r_cli/cmd_bomb.py](https://github.com/koval01/my_code/blob/master/b0mb3r_cli/cmd_bomb.py)

**Comment by crinny** [comment]
Добавил в [вики](https://github.com/crinny/b0mb3r/wiki/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B%2C-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D1%8E%D1%89%D0%B8%D0%B5-b0mb3r)
