### ISSUE TITLE
Разъясните нормально что да как установить!

### ISSUE THREAD

**Issue by Slivondiy** [crinny/b0mb3r#12]
Бля, я не такой хакер и х*я не понял как устанавливать! Разъясните пж!

**Comment by Slivondiy** [comment]
Ввожу в консоль Termux всё, нихуя не робит!

**Comment by vuchaev2015** [comment]
pkg install python
pkg install git
git clone https://github.com/crinny/b0mb3r
cd b0mb3r
pip install -r requirements.txt
python main.py

**Comment by Slivondiy** [comment]
Как выключить?

**Comment by Slivondiy** [comment]
Помогите пж

**Comment by Slivondiy** [comment]
> pkg установить python 
> pkg установить git 
> git clone https://github.com/crinny/b0mb3r
> cd b0mb3r 
> pip install -r 
> needs.txt python main.py

Помоги, как выключить?)

**Comment by Gwinbleiddd** [comment]
Обнови страницу. И/или выключи консоль.

**Comment by Gwinbleiddd** [comment]
Для запуска надо вводить cd b0mb3r
python main.py

**Comment by Slivondiy** [comment]
Ок спа

**Comment by Slivondiy** [comment]
Получается, просто выйти из termux она перестанет работать?)

**Comment by Gwinbleiddd** [comment]
Да.

**Comment by Gwinbleiddd** [comment]
Может еще вверху(В слайдере) понадобится нажать Exit

**Comment by Slivondiy** [comment]
> Может еще вверху(В слайдере) понадобится нажать Exit

ок спс
