### ISSUE TITLE
тоже не робит

### ISSUE THREAD

**Issue by Maxim133133** [crinny/b0mb3r#16]
Все ввел через git cmd, на последнем этапе кидает на сайт бота, но он тупо не грузит. С чем это связано?

**Comment by crinny7** [comment]
Что? На сайт бота? Приложи лог и скинь ссылку на этот сайт бота

вс, 11 авг. 2019 г., 13:10 Maxim133133 <notifications@github.com>:

**Comment by Maxim133133** [comment]
![image](https://user-images.githubusercontent.com/53994307/62832744-7cda7380-bc44-11e9-971a-b0faee4f4a61.png)
C:\Users\Максим\b0mb3r>python main.py
 * Listening on http://192.168.0.105:8080/
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

**Comment by crinny7** [comment]
Скопируй http://192.168.0.105:8080/ и вставь в строку браузера (не в поиск)

вс, 11 авг. 2019 г., 13:30 Maxim133133 <notifications@github.com>:

**Comment by Maxim133133** [comment]
Тоже самое, так же не грузит

**Comment by crinny** [comment]
> 
> 
> Тоже самое, так же не грузит

Есть возможность проверить в другом браузере?

**Comment by Maxim133133** [comment]
Я в хроме и в яндексе смотрел, нигде не грузит

**Comment by crinny** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/53994307/62832744-7cda7380-bc44-11e9-971a-b0faee4f4a61.png)

Что показывает Техническая информация?

**Comment by Maxim133133** [comment]
Техническая информация: ошибка connectionfailure

**Comment by crinny** [comment]
> 
> 
> Техническая информация: ошибка connectionfailure

Попробуй перезапустить бомбер и кэш браузера (Ctrl+F5)

**Comment by Maxim133133** [comment]
Щас попробую

**Comment by Maxim133133** [comment]
Тоже самое

**Comment by gugipar17** [comment]
Странно, если такое бывало, значит другая программа мешает работе. 
Попробуй отключить брандмауэр, если такой есть. ( В панели управления )

**Comment by Maxim133133** [comment]
Да. Отключение брандмауэра помогло
