### ISSUE TITLE
Автор мудила

### ISSUE THREAD

**Issue by VasyaDolmat1917** [crinny/b0mb3r#20]
Ахахахахха, блядь. Main.py у него. Иди аниме смотреть дальше, долбан, и срать себе в штаны

**Comment by crinny7** [comment]
Спасибо, посмеялся

вт, 13 авг. 2019 г., 21:48 VasyaDolmat <notifications@github.com>:

**Comment by crinny** [comment]
![изображение](https://user-images.githubusercontent.com/42045258/63003029-fc07bb80-be7f-11e9-90d1-04ec0cf47ea0.png)
