### ISSUE TITLE
Добавление SMS-сервиса

### ISSUE THREAD

**Issue by murmurshik** [crinny/b0mb3r#24]
Я тут один sms бомбер крякнул(питон), можешь от туда повыдёргивать)
[TBomb-master.zip](https://github.com/crinny/b0mb3r/files/3524266/TBomb-master.zip)
Всё в файле bomber.py там некоторые ф-ии переименованы(типо безопасность), но там все понятно.

**Comment by murmurshik** [comment]
Еще хочу сказать большое спасибо, ты(вы) проделал(и) большую работу. Первое, что пришло в голову, это то, что это фрэймворк для смс бомберов, настолько все круто)

**Comment by crinny** [comment]
Я его уже декомпилировал и выкладывал на своём канале в телеграме) Всё, что могло представлять для меня интерес уже оттуда взял. Но всё равно спасибо!
