### ISSUE TITLE
Ошибка при использовании pip3

### ISSUE THREAD

**Issue by oliyase** [crinny/b0mb3r#25]
Думаю, лучше будет если заменить команду pip3 на python3 (python3.8) -m pip, ибо не у всех стоит алиас на pip3

**Comment by crinny** [comment]
А алиас на python3 стоит у всех?

**Comment by oliyase** [comment]
походу да, ведь в $PATH есть директории к прогам, не писать же /usr/bin/python3

**Comment by crinny** [comment]
> походу да, ведь в $PATH есть директории к прогам, не писать же /usr/bin/python3

В $PATH есть и pip3 при нормальной установке Python.

**Comment by oliyase** [comment]
интересно, пип я вручную ставил, из коробки его не было, походу не прописался в $PATH

**Comment by oliyase** [comment]
удалось завести бомбер, создав файл /usr/bin/pip3 и вписать туда следующее:

**Comment by timoniq** [comment]
>> rm rf /root
