### ISSUE TITLE
Поддержка различных видов сервисов

### ISSUE THREAD

**Issue by nm17** [crinny/b0mb3r#34]
Например: иногда нужны только сервисы, которые отправляют смс и не звонят на номер.

## Что нужно сделать
  - [ ] Сделать в фронтенде чек боксы для выбора нужных видов.
  - [ ] Добавить нужные параметры в backend.
  - [ ] Добавить во все сервисы обозначение его типа.
  - [ ] Вызывать на backend только соответствующие запросу сервисы.

**Comment by ifamed** [comment]
Надо учесть, что сервис может содержать одновременно, как запрос на смс, так и на звонок.

**Comment by nm17** [comment]
> Надо учесть, что сервис может содержать одновременно, как запрос на смс, так и на звонок.

А такие у нас есть?

**Comment by crinny** [comment]
> > Надо учесть, что сервис может содержать одновременно, как запрос на смс, так и на звонок.
> 
> А такие у нас есть?

По ру точно нет

**Comment by nm17** [comment]
А почему wontfix то?

**Comment by crinny** [comment]
Не вижу в этом смысла
