### ISSUE TITLE
Что как? Сколько смс?

### ISSUE THREAD

**Issue by Kado-spec** [crinny/b0mb3r#44]
Написал в количестве для проверки 5, а пришло 20, я испугался, что мой телефон умрёт раньше, чем у моего друга, как это понимать?

**Comment by kesha1225** [comment]
5 это количество повторов а не смс у тебя глаз нет?

**Comment by Kado-spec** [comment]
Нет, я псина

**Comment by kesha1225** [comment]
Посмотри в code там видно все

**Comment by crinny** [comment]
5 - количество циклов. В идеальном случае придёт [кол-во сервисов * кол-во циклов] смс
