### ISSUE TITLE
Добавь злом жопы 

### ISSUE THREAD

**Issue by 0susboy0** [crinny/b0mb3r#45]
когда бомбер 3?

**Comment by sliva-cloud** [comment]
бля мудаки вы заебали спамить

**Comment by kesha1225** [comment]
> бля мудаки вы заебали спамить

эм пошел нахуй

**Comment by sliva-cloud** [comment]
ты иди нахуй

**Comment by 0susboy0** [comment]
слыш ты, слива ебаная

**Comment by 0susboy0** [comment]
### сам нахуй иди

**Comment by sliva-cloud** [comment]
нет ты нахуй иди, не засирай тред сука

**Comment by 0susboy0** [comment]
ясно, дурачок... ты кто по жизни? а? а? а?

**Comment by sliva-cloud** [comment]
ебаные уведомления на почту из-за таких мудаков как ты нужно отписываться от репа

**Comment by 0susboy0** [comment]
лох

**Comment by 0susboy0** [comment]
лох

**Comment by 0susboy0** [comment]
лох

**Comment by 0susboy0** [comment]
лохлох

**Comment by 0susboy0** [comment]
лох

**Comment by 0susboy0** [comment]
лох

**Comment by 0susboy0** [comment]
лох

**Comment by 0susboy0** [comment]
блин слился да лох га га га
