### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by combitoo** [crinny/b0mb3r#46]
Не видит файла, хотя он есть.
Консоль пытался запускать от имени админа. Ничего не помогает.

**Comment by crinny** [comment]
Скинь вывод команды `dir`, когда ты находишься в директории бомбера

**Comment by combitoo** [comment]
Содержимое папки C:\Windows\System32\b0mb3r

21.09.2019  14:18    <DIR>          .
21.09.2019  14:18    <DIR>          ..
21.09.2019  14:18    <DIR>          .github
21.09.2019  14:18                25 .gitignore
21.09.2019  14:18    <DIR>          assets
21.09.2019  14:18            35 823 LICENSE
21.09.2019  14:18             2 958 main.py
21.09.2019  14:18             3 449 README.md
21.09.2019  14:18                31 requirements.txt
21.09.2019  14:18    <DIR>          services
21.09.2019  14:18    <DIR>          static
21.09.2019  14:18    <DIR>          templates
               5 файлов         42 286 байт
               7 папок  397 653 565 440 байт свободно

**Comment by crinny** [comment]
Запускаешь остальные команды в той же директории?

**Comment by combitoo** [comment]
Нет. Все кроме git clone https://github.com/crinny/b0mb3r

**Comment by newpotsdev** [comment]
Замени эту команду на
```
python -m pip install requests flask fake_useragent
```
Она выполнит все тоже самое.

**Comment by crinny** [comment]
Закрыл за отсутсвием активности (бомбер тоже по той же причине можно закрыть, но я правда его делаю 🌚)
