### ISSUE TITLE
Возможно стоило бы хранить сервисы в словаре?

### ISSUE THREAD

**Issue by Bloodielie** [crinny/b0mb3r#49]
Не вижу особого смысла в этой куче файлов.

**Comment by crinny** [comment]
Нет.

**Comment by Bloodielie** [comment]
Какие есть преимущества у классов?

**Comment by Bloodielie** [comment]
Словари в работают в разы быстрее классов. Запуск атаки на телефоне осуществлялся бы в разы быстрее. Так же скорее всего программы бы потребляла меньшее количество памяти(не значительно)

**Comment by crinny** [comment]
Ассемблер работает в разы быстрее питона. Запуск атаки на телефоне осуществлялся бы в разы быстрее. Так же скорее всего программы бы потребляла меньшее количество памяти
