### ISSUE TITLE
Хочу пример запроса к api

### ISSUE THREAD

**Issue by kesha1225** [crinny/b0mb3r#5]
крини добавь пример запроса а то не красиво и типы даже в табличке значений для запроса не указаны ничего не понятно!!!!!!!!!!!!!!!

**Comment by catofsof** [comment]
> крини добавь пример запроса а то не красиво и типы даже в табличке значений для запроса не указаны ничего не понятно!!!!!!!!!!!!!!!

да я полностью согласен котик!! нужна дока подробнее!!!!!!!!!!!!!!!!!!!!!!!

**Comment by crinny** [comment]
> 
> да я полностью согласен котик!! нужна дока подробнее!!!!!!!!!!!!!!!!!!!!!!!

валяй пулл реквест

**Comment by catofsof** [comment]
нет не хочу

> > да я полностью согласен котик!! нужна дока подробнее!!!!!!!!!!!!!!!!!!!!!!!
> 
> валяй пулл реквест

**Comment by crinny** [comment]
> нет не хочу
> 
> > > да я полностью согласен котик!! нужна дока подробнее!!!!!!!!!!!!!!!!!!!!!!!
> > 
> > 
> > валяй пулл реквест

и че доебался тогда

**Comment by catofsof** [comment]
прости что доебался кринни............... твой бомбер лучший......................

**Comment by crinny** [comment]
> прости что доебался кринни............... твой бомбер лучший......................

спасибо люблю
