### ISSUE TITLE
Didn't work in the Termux

### ISSUE THREAD

**Issue by VLADIS-py** [crinny/b0mb3r#53]
Hello! Termux write me this is:
pip3 install b0omb3r -e

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...
Help please. Thanks.

**Comment by YamkaFox** [comment]
# In Termux use

```bash
pip3 install b0mb3r -U
```

**Comment by YamkaFox** [comment]
Please close this issue and comment my answer like

**Comment by VLADIS-py** [comment]
> Пожалуйста, закройте эту проблему и прокомментируйте мой ответ как

This is command didn't work. Termux write me this:
pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -u

**Comment by crinny** [comment]
> > Пожалуйста, закройте эту проблему и прокомментируйте мой ответ как
> 
> This is command didn't work. Termux write me this:
> pip3 install [options] [package-index-options] ...
> pip3 install [options] -r [package-index-options] ...
> pip3 install [options] [-e] ...
> pip3 install [options] [-e] ...
> pip3 install [options] <archive url/path> ...
> 
> no such option: -u

The -U is capital letter. Please, just copy and paste the command.

**Comment by VLADIS-py** [comment]
Ooowww.... Sorry, I realized this a second before your answer, sorry again.
