### ISSUE TITLE
Неверное поведение при параллельном использовании инстанса бомбера >1 человеком

### ISSUE THREAD

**Issue by crinny** [crinny/b0mb3r#54]
**Шаги воспроизведения**
1. Запустите бомбер
2. Откройте инстанс в двух вкладках браузера и запустите атаки

**Фактический результат**
Прогрессбары ведут себя, будто бахнув пельменей

**Ожидаемый результат**
Прогрессбары атак показывают независимое содержание

**Устройство**
 - Операционная система: N/A
 - Браузер N/A

**Comment by crinny** [comment]
Решение: при запуске атаки (`/attack/start`) передавать уникальный ID, сохраняемый на стороне клиента и используемый для получения статуса

**Comment by nm17** [comment]
@crinny и где id и атаки хранить то

**Comment by crinny** [comment]
> @crinny и где id и атаки хранить то

Почему не подходит dict?

**Comment by kurkanduk** [comment]
Привет, кароч запускаю на одного человека бомбер, и всё. Сообщения приходят, но прогрессбар ведёт себя не как бахнул пельменей, а как бахнул водки. Притом раньше он прямо летал, а сейчас чёт как то не очень...

**Comment by crinny** [comment]
> Привет, кароч запускаю на одного человека бомбер, и всё. Сообщения приходят, но прогрессбар ведёт себя не как бахнул пельменей, а как бахнул водки. Притом раньше он прямо летал, а сейчас чёт как то не очень...

Не относится к этому issue.
