### ISSUE TITLE
Прогрессбар не отображается на некоторых устройствах

### ISSUE THREAD

**Issue by nm17** [crinny/b0mb3r#55]
**Шаги воспроизведения**
1. Запустите бомбер 
2. Введите данные
3. Нажмите "начать атаку"

**Фактический результат**
При попытке запустить бомбер, ничего не происходит.
Видео @y9san9 в тг (https://t.me/b0mb3r4at/49861)
https://youtu.be/Y8LXCjRvJwg

**Ожидаемый результат**
При нажатии "Начать атаку" бомбер должен запустить атаку.

**Устройство**
 - Операционная система: Android 10; Mi 9T
 - Браузер: Chrome 80.0.3987.149

Работает спокойно на ПК

**Comment by crinny** [comment]
Не воспроизводится на Redmi Note 7, Chrome 80.0.3987.162

**Comment by y9san9** [comment]
после переустановки также ничего не поменялось. также замечание, что бомбер запущен и смски идут. баг только визуальный

**Comment by crinny** [comment]
Воспроизвелось на Windows 10, Chrome 80.0.3987.163

**Comment by catofsof** [comment]
Не воспроизводится на Redmi Note 7. Chrome версии 81.0.4044.96.

**Comment by crinny** [comment]
Закрываю за отсутствием активности.

**Comment by y9san9** [comment]
и всё равно не могу юзать бомбер из-за этого бага бтв

**Comment by y9san9** [comment]
Обновился до ласт версии. Бага нет, почему я иссью сам закрыть не могу ?
