### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by hum4not** [crinny/b0mb3r#56]
после открытия 127.0.0.1:8080, выдает ошибку в консоли  "utf 8 codec can't decode byte 0x84",а на сайте же в этот момент 500 internal server error, Server got itself in trouble.

**Устройство**
 - Операционная система: Windows 10
 - Браузер chrome

**Comment by crinny** [comment]
Полный текст ошибки, пожалуйста

**Comment by hum4not** [comment]
![error](https://user-images.githubusercontent.com/63611146/79550422-be63ce00-80b1-11ea-9050-c457c7160760.jpg)

**Comment by hum4not** [comment]
> Полный текст ошибки, пожалуйста

отправил выше

**Comment by crinny** [comment]
Переустановка не помогает? Какая версия windows?

**Comment by hum4not** [comment]
> Переустановка не помогает?

я только --repair пробовал, сейчас попробую полностью переустановить

**Comment by hum4not** [comment]
> Переустановка не помогает?

неа, не помогает

**Comment by crinny** [comment]
@hum4not воспроизводится после обновления?
