### ISSUE TITLE
Возможность выбора порта

### ISSUE THREAD

**Issue by isamarin** [crinny/b0mb3r#58]
Если на устройстве 8080 порт занят, то тулза просто крашится. Нужна возможность ручного выбора порта при запуске

**Comment by nm17** [comment]
Она есть https://github.com/crinny/b0mb3r/wiki/%D0%90%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%BE%D0%B9-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8
