### ISSUE TITLE
Сервисез

### ISSUE THREAD

**Issue by traxadze** [crinny/b0mb3r#62]
- [x] https://kursk.sushi-master.ru/menu/rolly
 - [x] https://fix-price.ru/auth/register.php
 - [x] https://auth.auto.ru
 - [x] https://clck.ru/NLh56 - sravni.ru
 - [x] https://050taxi.ru/
 - [x] https://planetazdorovo.ru/lk/signin/
 - [x] https://zdravcity.ru/g_paracetamol/r_moscowregion/
 - [x] https://сушивесла.рф/
 - [x] https://clck.ru/NLh4P - moyareklama.ru
 - [x] https://clck.ru/NLh3a - oldi.ru
 - [x] https://www.rbt.ru/user/reg/
 - [x] https://volgograd.abc.ru/registration/
 - [x] https://cenalom.ru/reg
 - [x] https://esh-derevenskoe.ru/
 - [ ] https://clck.ru/NLh2Z - wowfood.pro
 - [ ] https://sovest.ru/partners/edayandex
 - [ ] https://posudamart.ru/account/login
 - [ ] https://levelkitchen.com/
 - [ ] https://www.chefmarket.ru/
 - [ ] https://mygiftcard.ru/login/
 - [ ] https://sushiwok.ru/msk/
 - [ ] https://dostaevsky.ru/
 - [ ] https://mcdonalds.ru/menu/delivery
 - [ ] https://kdvonline.ru/signin
 - [ ] https://vkusvill.ru/
 - [ ] https://tvoydom.ru/
 - [ ] https://www.petshop.ru/catalog/cats/syxkor/
 - [ ] https://www.cafemumu.ru/delivery/#
 - [ ] https://www.gloria-jeans.ru/help/delivery
 - [ ] https://grilnica.ru/login/
 - [ ] https://www.pronto24.ru/
 - [ ] https://eda.sakh.com/?hl=ru
 - [ ] https://www.kant.ru/help/shipping/
 - [ ] https://goldapple.ru/dostavka-i-oplata
 - [ ] https://ginzadelivery.ru/restaurants/danilovskymarket/popular
 - [ ] https://svoya-kompaniya.ru/menu
 - [ ] https://2-berega.ru/
 - [ ] https://localkitchen.ru/

**Comment by jetoz** [comment]
обьясните тупому как это устанавливать типо писать?

**Comment by doubledare704** [comment]
> обьясните тупому как это устанавливать типо писать?

в проекте есть папка сервисы и в ней в каждом файле живут аля решения, где происходит пост или гет запрос на указанную ссылку. Суть добавления сервисов: унаследовать класс сервис, как во всех файлах и провести гет или пост запрос, смотря что принимает реальный сайт

**Comment by aiexz** [comment]
sravni.ru капча

**Comment by VladFill1506** [comment]
228

**Comment by nm17** [comment]
Закрываю, ибо большинство не работает. Скоро будут новые.
