### ISSUE TITLE
Добавление SMS-сервиса

### ISSUE THREAD

**Issue by makarhuyaker** [crinny/b0mb3r#67]
Telegram

**Comment by catofsof** [comment]
TelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegramTelegram

**Comment by crinny** [comment]
Telegram Telegram Telegram
