### ISSUE TITLE
Не работает в Termux, Python 3.8

### ISSUE THREAD

**Issue by berkovskiy** [crinny/b0mb3r#68]
**Шаги воспроизведения**
Проверил в Termux на Python 3,8 - Не работает. Не инсталлируется проект. Попробовал, все так же в Termux на Python 3.7.* - все норм работает  

**Устройство**
 - Операционная система: Android
 - Браузер N/A

**Comment by crinny** [comment]
@berkovskiy залей ошибки на hastebin.com

**Comment by berkovskiy** [comment]
@crinny https://pastebin.com/uSZA4Ry3
В хастебин не работает чет.

**Comment by crinny** [comment]
@berkovskiy следовал инструкции? особенно первой команде?
```
pkg install python clang make -y
```

**Comment by berkovskiy** [comment]
Что сделал - на Python 3.8 не получилось вообще, создал виртуальное окружение с Python 3.7.*, в нем НЕ выполняя pkg install python clang make -y выполнил pip3 install b0mb3r -U, ИТОГ - отработал без проблем, сервис поднялся...
Создал еще одно виртуальное окружение с Python 3.8 выполнил pkg install python clang make -y, pip3 install b0mb3r -U - все поднялось. 
Как так?) почему без виртуалки появляются ошибки? Конфликт либ?

**Comment by catofsof** [comment]
видимо, ты не установил make. 
что ввёл я для того, чтобы получить точно такую же ошибку: 
```pkg i python clang -y```
```pip install b0mb3r```

получил: https://pastebin.com/mRJr7Se4

читайте документацию и всё будет работать хорошо.

**Comment by berkovskiy** [comment]
@catofsof прикол в том, что я создал виртуальное окружение (голое)... Все заработало. 
Без окружения не работало. В любом случае спасибо за обратную связь. Надеюсь помогу чем нибудь )
