### ISSUE TITLE
ошибка elinks

### ISSUE THREAD

**Issue by sudo-gera** [crinny/b0mb3r#70]
**Шаги воспроизведения**
1. Установите elinks в termux
2. Запустите бомбер как обычно 

**Фактический результат**
сайт 8080 не работает

**подробное описание**
браузер elinks останавливает поток выполнения, что означает, что сервер запустится только после закрытия этого браузера. Не гарантирую, что это единственный такой браузер. Если он установлен по умолчанию, то это плохо, я только знаю как это обработать в термуксе. https://photos.app.goo.gl/W5TmnMzEZqjkhgH76 тут моя версия решения проблемы только для термукса.

**Comment by cxiodev** [comment]
Попробуйте запустить две сессии Termux, в одном b0mb3r, во втором elinks.
