### ISSUE TITLE
Ошибка поддержки utf8 символов

### ISSUE THREAD

**Issue by qbaddev** [crinny/b0mb3r#8]
B0
![photo_2019-08-07_21-09-44](https://user-images.githubusercontent.com/38311102/62646779-bf0b6880-b957-11e9-8147-cd724f273194.jpg)
mb3r не хочет поддерживать utf8 символы выдавая ошибку.

**Comment by qbaddev** [comment]
b0mb3r*

**Comment by crinny** [comment]
Работаю над этим.

**Comment by qbaddev** [comment]
> Работаю над этим.

Хорошо , жду фикса.

**Comment by olegoleg1111121** [comment]
не твой бомбер чорт
уеба удали быстро, у нас не покупают(((((

**Comment by crinny** [comment]
> 
> 
> не твой бомбер чорт
> уеба удали быстро, у нас не покупают(((((

капец вы лохи)
