### ISSUE TITLE
Кнопка обновления сервисов без перезапуска приложения

### ISSUE THREAD

**Issue by newdarkstar** [crinny/b0mb3r#80]
Крини добавь пж кнопку reload для сервисов в веб апп, при тестировании новых сервисов бесит каждый раз перезапускать бомбер в консоли(

**Comment by newdarkstar** [comment]
wontfix ;(

**Comment by Exodus-exe** [comment]
Я не кринни

вт, 14 июл. 2020 г., 20:00 D4RKST4R <notifications@github.com>:
