### ISSUE TITLE
4** ошибки по всем сервисам

### ISSUE THREAD

**Issue by MaksSharkov** [crinny/b0mb3r#89]
**Шаги воспроизведения**
1. Запустить бомбер из терминала
2. Ввести номер и запустить на любом кол-ве циклов

**Фактический результат**
Сервисы кидают 4** ошибки

**Ожидаемый результат**
Успешная рассылка

**Устройство**
 - Операционная система: Android 8 + Termux, ArchLinux, Windows 10
 - Браузер Chrome, Yandex, Firefox

Пробовал различные VPN. От своих тачек за бугром, до общедоступных российских, пробовал с домашнего интернета напрямую (МТС), с Android (Yota) через Termux. Везде результат одинаковый. Четырёхсотые ошибки по всем сервисам.
![image](https://user-images.githubusercontent.com/18408143/89228606-9bb9de80-d5e8-11ea-806c-18698ade1483.png)

**Comment by xcaq** [comment]
эх крини... штош ты так...

**Comment by MaksSharkov** [comment]
@crinny в чатике сказали, что можно ткнуть тебя :)

**Comment by xcaq** [comment]
> @crinny в чатике сказали, что можно ткнуть тебя :)

нельзя, крини отдыхает с виталей

**Comment by crinny** [comment]
Связано с мёртвыми сервисами, на работоспособность не влияет.

**Comment by MaksSharkov** [comment]
> Связано с мёртвыми сервисами, на работоспособность не влияет.

А живые пополняться будут? Или это уже забота персонально юзеров? ))

**Comment by crinny** [comment]
Будут и постоянно пополняются
