### ISSUE TITLE
Не флудит, просто одни ошибки в лог

### ISSUE THREAD

**Issue by ktxdev** [crinny/b0mb3r#95]
![Screenshot_20200815-130732](https://user-images.githubusercontent.com/38311102/90310260-ab92c600-def8-11ea-9bcd-f1b5d4f81d9d.png)

**Comment by crinny** [comment]
https://github.com/crinny/b0mb3r/wiki/Когда-что-то-идёт-не-так#Много-ошибок-в-логах

**Comment by ktxdev** [comment]
Не пришло ни одного сообщения.

**Comment by crinny** [comment]
Значит сервисы мертвы
